version: "3.8"


networks:
  frontend: {}
  backend: {}

volumes:
  km_data:


services:
  gateway:
    container_name: gateway
    build:
      context: ./gateway/development
      dockerfile: ./Dockerfile
    networks:
      - frontend
    ports:
      - 443:443
    volumes:
      - ./gateway/development/conf.d/:/etc/gateway/conf.d/
    depends_on:
      - server
      - ui

  postgres:
    container_name: postgres
    image: postgres:alpine
    logging:
      options:
        max-size: "10m"
        max-file: "3"
    environment:
      POSTGRES_PASSWORD: vL1NVXu6T
    volumes:
      - km_data:/var/lib/postgresql/data
    networks:
      - backend
    ports:
      - 5432:5432


  server:
    container_name: server
    build:
      context: ./api
      dockerfile: ./Dockerfile.dev
    volumes:
      - ./api/src:/opt/app
    depends_on:
      - "postgres"
    logging:
      options:
        max-size: "10m"
        max-file: "3"
    networks:
      - backend
      - frontend
    ports:
      - 8080:8080

  ui:
    container_name: ui
    build:
      context: ./client
      dockerfile: Dockerfile
    volumes:
      - ./client:/opt/app
    logging:
      options:
        max-size: "10m"
        max-file: "3"
    stdin_open: true
    networks:
      - frontend
    ports:
      - 4200:4200

